APT::FTPArchive::Release::Origin "termgram-apt";
APT::FTPArchive::Release::Label "Termgram APT";
APT::FTPArchive::Release::Suite "stable";
APT::FTPArchive::Release::Codename "stable";
APT::FTPArchive::Release::Architectures "aarch64 all";
APT::FTPArchive::Release::Components "main";
