APT::FTPArchive::Release::Origin "termgram-apt";
APT::FTPArchive::Release::Label "Termgram APT";
APT::FTPArchive::Suite "termgram-unofc";
APT::FTPArchive::Codename "termgram-unofc";
APT::FTPArchive::Architectures "aarch64 all";
APT::FTPArchive::Components "main";
